AddCSLuaFile("cl_init.lua")
AddCSLuaFile("cl_room.lua")
AddCSLuaFile("cl_ships.lua")
AddCSLuaFile("sh_bounds.lua")
AddCSLuaFile("gui/cl_matrix.lua")
AddCSLuaFile("gui/cl_transform2d.lua")
AddCSLuaFile("gui/cl_slider.lua")
AddCSLuaFile("gui/cl_button.lua")
AddCSLuaFile("gui/cl_tabmenu.lua")
AddCSLuaFile("sh_systems.lua")

include("sv_init.lua")
