AddCSLuaFile("cl_init.lua")
AddCSLuaFile("cl_door.lua")
AddCSLuaFile("cl_room.lua")
AddCSLuaFile("cl_ship.lua")
AddCSLuaFile("cl_ships.lua")
AddCSLuaFile("cl_universe.lua")
AddCSLuaFile("cl_scoreboard.lua")
AddCSLuaFile("sh_teams.lua")

include("sv_init.lua")
