AddCSLuaFile("cl_init.lua")
AddCSLuaFile("cl_door.lua")
AddCSLuaFile("cl_room.lua")
AddCSLuaFile("cl_ship.lua")
AddCSLuaFile("cl_ships.lua")
AddCSLuaFile("sh_bounds.lua")
AddCSLuaFile("cl_matrix.lua")
AddCSLuaFile("cl_transform2d.lua")
AddCSLuaFile("sh_gui.lua")
AddCSLuaFile("sh_systems.lua")

include("sv_init.lua")
